environs:
  dataset_root: '/mnt/shared/dataset'
  thresh_root: 'config/threshes'
  dataset_name: 'auburn'
  subsets: ['fri001', 'fri003', 'fri005']
#            'sat001am', 'sat002am', 'sat005pm', 'sat006pm']
mongo:
  host: localhost
  port: 27017
inference:
  type: yolo
differencer:
  use_dict: true
  types: [pixel, area, edge]
motioner:
  type: adapative_bg_learning
evaluator:
  - type: coco
    class: [0]
  - type: coco
    class: [2]
  - type: coco
    class: [0, 2]
  - type: counting
    class: [0]
  - type: counting
    class: [2]
  - type: counting
    class: [0, 2]
  - type: tagging
    class: [0]
  - type: tagging
    class: [2]
  - type: tagging
    class: [0, 2]
