- name: ssd_mobilenet_v1_coco
  trained_name: ssd_mobilenet_v1_coco_2018_01_28
  speed: 30
  mAP: 21
- name: ssd_mobilenet_v1_0.75_depth_coco
  trained_name: ssd_mobilenet_v1_0.75_depth_300x300_coco14_sync_2018_07_03
  speed: 30
  mAP: 18
- name: ssd_mobilenet_v1_quantized_coco
  trained_name: ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18
  speed: 29
  mAP: 18
- name: ssd_mobilenet_v1_0.75_depth_quantized_coco
  trained_name: ssd_mobilenet_v1_0.75_depth_quantized_300x300_coco14_sync_2018_07_18
  speed: 29
  mAP': 16
- name: ssd_mobilenet_v1_ppn_coco
  trained_name: ssd_mobilenet_v1_ppn_shared_box_predictor_300x300_coco14_sync_2018_07_03
  speed: 26
  mAP: 20
- name: ssd_mobilenet_v1_fpn_coco
  trained_name: ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03
  speed: 56,
  mAP: 32
- name: ssd_resnet_50_fpn_coco
  trained_name: ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03
  speed: 76,
  mAP: 35
- name: ssd_mobilenet_v2_coco
  trained_name: ssd_mobilenet_v2_coco_2018_03_29
  speed: 31,
  mAP: 22
- name: ssd_mobilenet_v2_quantized_coco
  trained_name: ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03
  speed: 29,
  mAP: 22
- name: ssdlite_mobilenet_v2_coco
  trained_name: ssdlite_mobilenet_v2_coco_2018_05_09
  speed: 27,
  mAP: 22
- name: ssd_inception_v2_coco
  trained_name: ssd_inception_v2_coco_2018_01_28
  speed: 42,
  mAP: 24
- name: faster_rcnn_inception_v2_coco
  trained_name: faster_rcnn_inception_v2_coco_2018_01_28
  speed: 58,
  mAP: 28
- name: faster_rcnn_resnet50_coco
  trained_name: faster_rcnn_resnet50_coco_2018_01_28
  speed: 89,
  mAP: 30
- name: faster_rcnn_resnet50_lowproposals_coco
  trained_name: faster_rcnn_resnet50_lowproposals_coco_2018_01_28
  speed: 64,
  mAP: -1
- name: rfcn_resnet101_coco
  trained_name: rfcn_resnet101_coco_2018_01_28
  speed: 92,
  mAP: 30
- name: faster_rcnn_resnet101_coco
  trained_name: faster_rcnn_resnet101_coco_2018_01_28
  speed: 106,
  mAP: 32
- name: faster_rcnn_resnet101_lowproposals_coco
  trained_name: faster_rcnn_resnet101_lowproposals_coco_2018_01_28
  speed: 82,
  mAP: -1
- name: faster_rcnn_inception_resnet_v2_atrous_coco
  trained_name: faster_rcnn_inception_resnet_v2_atrous_coco_2018_01_28
  speed: 620,
  mAP: 37
- name: faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco
  trained_name: faster_rcnn_inception_resnet_v2_atrous_lowproposals_coco_2018_01_28
  speed: 241,
  mAP: -1
- name: faster_rcnn_nas
  trained_name: faster_rcnn_nas_coco_2018_01_28
  speed: 1833
  mAP: 43
- name: faster_rcnn_nas_lowproposals_coco
  trained_name: faster_rcnn_nas_lowproposals_coco_2018_01_28
  speed: 540,
  mAP: -1
